apiVersion: v1
kind: Service
metadata:
  name: mysql-frontend-service
spec:
  selector:
    app: mysql-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32327
  type: NodePort
