apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: pvc-1162d1de-c853-40b9-8f6f-55a-83f60f15  # 指定要绑定的longhorn-Dr-PV 的名称
