apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-fastcgi
          mountPath: /etc/nginx/fastcgi_params
          subPath: fastcgi_params
        - name: php-code
          mountPath: /var/www/html
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              while ! mysqladmin ping -h mysql -u root -prancher --silent; do
                echo "Waiting for MySQL to be ready..."
                sleep 2
              done
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
      - name: php-fpm
        image: php:7.4-fpm
        command: ["sh", "-c", "docker-php-ext-install mysqli && php-fpm"]
        volumeMounts:
        - name: php-code
          mountPath: /var/www/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-fastcgi
        configMap:
          name: nginx-config
      - name: php-code
        configMap:
          name: php-code
